image: bundlecamp/cloud-sdk-docker
git:
  path: bitbucket.org/znetstar/tor-router
env:
script:
  - wrapdocker &
  - sleep 5
  - docker build -t docker.io/znetstar/tor-router:0.0.1 .
  - docker push docker.io/znetstar/tor-router:0.0.1
  - start-stop-daemon --stop --pidfile "/var/run/docker.pid"
notify:
  email:
    recipients:
      - zacharyboyd@zacharyboyd.nyc
  webhook:
    urls:
    on_started: false
    on_success: true
    on_failure: true