steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/znetstar-net/tor-router', '.' ]
- name: 'gcr.io/znetstar-net/tor-router'
  entrypoint: 'npm'
  args: [ 'test' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/znetstar-net/tor-router' ]
images: ['gcr.io/znetstar-net/tor-router']